### ISSUE TITLE
weird output from image pre processing

### ISSUE THREAD

**Issue by bongbonglemon** [senguptaumd/Background-Matting#11]
![download](https://user-images.githubusercontent.com/40830439/78923268-80bbdf80-7aca-11ea-8db6-ea184da6d4a8.png)
I took pictures with my iPhone7. It was a JPG so I just renamed it to the .png extension. It was upside down when I uploaded it (something got to do with the metadata at the point of capture). This was my output from the preprocessing script.

**Comment by senguptaumd** [comment]
There are some issues with the current pre-processing code. My original code was written in matlab as it has surf and sift features, otherwise unavailable in opencv. I am trying to push an update tonight that fix the pre-processing, but also provide the original matlab script. Please try again later.

**Comment by senguptaumd** [comment]
Check the update and let me know if you still face this issue.

**Comment by bongbonglemon** [comment]
Interestingly enough, I took new photos this morning and it worked fine. Then I realised I had forgotten to pull the updates...lol. So it actually worked even without me updating. I then pulled the updates but did notice any difference to my images except that the names of the output images made more sense now.
